# ═══════════════════════════════════════════════════════════════════════
# AAM Backup Automation — Configuration Data Collector (PowerShell)
# Gathers network info, MAC addresses, and FY folder name.
# Output: Copy-paste ready YAML snippets for config.yaml
# ═══════════════════════════════════════════════════════════════════════

Set-StrictMode -Version Latest
$ErrorActionPreference = "SilentlyContinue"

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ProjectDir = Split-Path -Parent $ScriptDir

Write-Host ""
Write-Host "===================================================================="
Write-Host "  AAM Backup — Configuration Data Collector"
Write-Host "===================================================================="
Write-Host ""

# ── Network Adapters ─────────────────────────────────────────────────
Write-Host "[1/5] Gathering network adapter information..."
$adapters = Get-NetAdapter | Where-Object { $_.Status -eq "Up" }

$yaml = @()
$yaml += "# ═══════════════════════════════════════════════════"
$yaml += "# Auto-generated by collect_config.ps1"
$yaml += "# Paste relevant sections into config.yaml"
$yaml += "# ═══════════════════════════════════════════════════"
$yaml += ""
$yaml += "# ── Network Adapters ──"
$yaml += "network_adapters:"

foreach ($adapter in $adapters) {
    $ip = ($adapter | Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Select-Object -First 1).IPAddress
    $yaml += "  - name: `"$($adapter.Name)`""
    $yaml += "    mac: `"$($adapter.MacAddress)`""
    $yaml += "    ip: `"$ip`""
    $yaml += "    description: `"$($adapter.InterfaceDescription)`""
}
$yaml += ""

# ── Current FY Folder ────────────────────────────────────────────────
Write-Host "[2/5] Detecting current FY folder..."
$month = (Get-Date).Month
$year  = (Get-Date).Year
if ($month -ge 4) {
    $fyStart = $year % 100
    $fyEnd   = ($year + 1) % 100
} else {
    $fyStart = ($year - 1) % 100
    $fyEnd   = $year % 100
}
$currentFY = "FY{0:D2}-{1:D2}" -f $fyStart, $fyEnd

$yaml += "# ── Current FY ──"
$yaml += "# Source drive MUST end with the current FY folder"
$yaml += "current_fy: `"$currentFY`""
$yaml += "# Example source_drive:  `"D:\YOUR_DATA\$currentFY`""
$yaml += "# Example lan_destination:  `"\\NAS_IP\share\$currentFY`""
$yaml += ""

# ── GCS Bucket ───────────────────────────────────────────────────────
Write-Host "[3/5] Reading GCS bucket configuration..."
$yaml += "# ── GCS Bucket ──"
$yaml += "gcs_bucket: `"aam-cloudbackup`""
$yaml += "gcs_project: `"aam-backup-2026`""
$yaml += "gcs_service_account: `"aam-cloudbackup@aam-backup-2026.iam.gserviceaccount.com`""
$yaml += ""

# ── Server Info ──────────────────────────────────────────────────────
Write-Host "[4/5] Gathering server info..."
$hostname  = $env:COMPUTERNAME
$domain    = (Get-WmiObject Win32_ComputerSystem).Domain
$localIP   = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -ne "127.0.0.1" } | Select-Object -First 1).IPAddress

$yaml += "# ── Server Info ──"
$yaml += "hostname: `"$hostname`""
$yaml += "domain: `"$domain`""
$yaml += "server_ip: `"$localIP`""
$yaml += ""

# ── Ports ────────────────────────────────────────────────────────────
Write-Host "[5/5] Adding default port configuration..."
$yaml += "# ── Ports ──"
$yaml += "# Prefect server (default: 4200)"
$yaml += "prefect_port: 4200"
$yaml += "# Dashboard (default: 8080)"
$yaml += "dashboard_port: 8080"
$yaml += ""

# ── Output ───────────────────────────────────────────────────────────
$yaml += "# ═══════════════════════════════════════════════════"
$yaml += "# CONFIG.YAML — Paths Section"
$yaml += "# ═══════════════════════════════════════════════════"
$yaml += "paths:"
$yaml += "  source_drive: `"D:\YOUR_DATA\$currentFY`""
$yaml += "  lan_destination: `"\\10.10.186.231\lan_backup\$currentFY`""
$yaml += "  runtime_dir: `"C:\BackupAgent`""
$yaml += "  gcs_key_path: `"C:\AAM_BACKUP_V1\deploy\keys\aam-gcs-key.json`""

Write-Host ""
Write-Host "===================================================================="
Write-Host "  Collected Configuration Data"
Write-Host "===================================================================="
Write-Host ""

# Print to console
$yaml | ForEach-Object { Write-Host $_ }

# Save to file
$outFile = Join-Path $ProjectDir "config_snippet.yaml"
$yaml | Out-File -FilePath $outFile -Encoding UTF8
Write-Host ""
Write-Host "Saved to: $outFile"
Write-Host ""
Write-Host "Copy the relevant sections above into config.yaml"
Write-Host ""
pause
